**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [6]:
import numpy as np
array = np.random.randint(1, 101, 50) # de 50 numeros de 0 a 101
media = np.mean(array)
mediana = np.median(array)
desvio_padrao = np.std(array)
valor_max = np.max(array)
valor_min = np.min(array)

print(f"Array: {array}")

print("\n")

print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Desvio padrão: {desvio_padrao}")
print(f"Valor máximo: {valor_max}")
print(f"Valor mínimo: {valor_min}")

Array: [ 49 100   5  49   7  25  25  28  35   9  43  64   5  10  97  44  51  25
  91  48  22  45  23   7  95  52  80  98  12  79  66  20  56  66  84  56
   3  38  45  81  88  11  81  58  19  34  81  11  66  76]


Media: 47.26
Mediana: 46.5
Desvio padrão: 29.520033875319314
Valor máximo: 100
Valor mínimo: 3


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [23]:
import numpy as np

mat1 = np.random.randint(1, 11, (3, 3)) # de 1 até 11 com dimensões 3, 3
mat2 = np.random.randint(1, 11, (3, 3))

soma = mat1 + mat2
sub = mat1 - mat2
mult = mat1 * mat2
div = mat1 / mat2

print(f"Matriz 1:\n {mat1}")
print(f"Matriz 2:\n {mat2}")

print(f"Soma:\n {soma}\n")
print(f"Subtração:\n {sub}\n")
print(f"Multiplicação:\n {mult}\n")
np.set_printoptions(precision=2, suppress=True) # duas casas de precisão após a vírgula
print(f"Divisão:\n {div} \n")

Matriz 1:
 [[1 3 2]
 [7 4 4]
 [1 5 1]]
Matriz 2:
 [[2 8 9]
 [6 2 6]
 [1 8 9]]
Soma:
 [[ 3 11 11]
 [13  6 10]
 [ 2 13 10]]

Subtração:
 [[-1 -5 -7]
 [ 1  2 -2]
 [ 0 -3 -8]]

Multiplicação:
 [[ 2 24 18]
 [42  8 24]
 [ 1 40  9]]

Divisão:
 [[0.5  0.38 0.22]
 [1.17 2.   0.67]
 [1.   0.62 0.11]] 



**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [31]:
import numpy as np

matriz = np.random.randint(1, 21, (4, 4))

print(f"Matriz:\n {matriz}")

soma_linha = np.sum(matriz, axis=1) # 1 para somar linhas
print(f"Soma dos elementos das linhas: {soma_linha}")

soma_coluna = np.sum(matriz, axis=0) # 0 para somar colunas
print(f"Soma dos elementos das colunas: {soma_coluna}")

Matriz:
 [[ 6 18  9 12]
 [ 3 10  9  6]
 [17  2 14  1]
 [ 4  6 16 11]]
Soma dos elementos das linhas: [45 28 34 37]
Soma dos elementos das colunas: [30 36 48 30]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [52]:
import numpy as np

arrayteste = np.random.randint(0, 51, 30)

maiores = arrayteste[arrayteste > 25]
qntd = maiores.shape

print(f"Array completo:\n {arrayteste}")
print(f"Valores maiores que 25: {maiores}")

print(f"Quantidade de valores maiores que 25: {qntd}")

Array completo:
 [ 0  6 37 43 44 37 49 40 22 36 47 27 24 49 31 10 48 27  2 36 20 22 37 34
  2 32 47 22 24 41]
Valores maiores que 25: [37 43 44 37 49 40 36 47 27 49 31 48 27 36 37 34 32 47 41]
Quantidade de valores maiores que 25: (19,)


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [48]:
import numpy as np

matriz = np.random.randint(1, 11, (3, 3, 3))

soma = np.sum(matriz)
somacumulativa = np.cumsum(matriz)

print(f"Matriz completa:\n {matriz}\n")
print(f"Soma: {soma}\n")
print(f"Soma cumulativa:\n {somacumulativa}\n")

Matriz completa:
 [[[ 8  7  8]
  [ 6  1  9]
  [ 3  8  1]]

 [[10  5  8]
  [ 1  2  8]
  [10  7  8]]

 [[ 3  2  1]
  [ 1  6  5]
  [ 2  4  3]]]

Soma: 137

Soma cumulativa:
 [  8  15  23  29  30  39  42  50  51  61  66  74  75  77  85  95 102 110
 113 115 116 117 123 128 130 134 137]

